# 텍스트 전처리

# 1. 토큰화-나누기

## 1-1. 단어 토큰화
- 구두점( , . ! ? ' 등)이나 특수 문자를 단순 제외해서는 안 된다-> 의미를 가지고 있을수도 있으므로
- 줄임말(I'm)이나 띄어쓰기(rock 'n' roll)단순 분리도 조심

In [1]:
from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [8]:
text="Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a home-based shop."

print(word_tokenize(text))  #-> 구두점, 특수문자 대부분 분리
print(text_to_word_sequence(text))  #-> .은 제거하는데 '는 유지, 전부 소문자화

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'home-based', 'shop', '.']
["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'home', 'based', 'shop']


## 1-2. 표준토큰화 예제
- treebankwordtoeknizer사용
- 규칙 1. 하이푼으로 구성된 단어는 하나로 유지한다.
- 규칙 2. doesn't와 같이 아포스트로피로 '접어'가 함께하는 단어는 분리해준다.

In [3]:
from nltk.tokenize import TreebankWordTokenizer

In [7]:
tokenizer=TreebankWordTokenizer()  #객체 생성

print('트리뱅크:',tokenizer.tokenize(text))

트리뱅크: ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'home-based', 'shop', '.']


## 1-3. 문장 토큰화

In [10]:
from nltk.tokenize import sent_tokenize

text = "I am actively looking for Ph.D. students. and you are a Ph.D student."
print('문장 토큰화2 :',sent_tokenize(text))   #-> 단순 . 으로 구분X

문장 토큰화2 : ['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


# 2. 정제(Cleaning)와 정규화(Normalization)
- 정제(cleaning) : 갖고 있는 코퍼스로부터 노이즈 데이터(불필요한)를 제거한다.
- 정규화(normalization) : 표현 방법이 다른 단어들을 통합시켜서 같은 단어로 만들어준다.(US, USA)
- 대, 소문자 통합

## 2-1. 불필요한 단어 제거
- 등장 빈도가 적은 단어-> 필요할수도있지만 대량의 문서 분류시 도움이 안될 확률 큼
- 길이가 짧은 단어-> 한국어의 경우 어려움 but 영어의 경우 1~2자 제거는 도움됨 ex) I, a, it, at, to, on, by

In [31]:
# 그냥 1~2자 제거하기
import re
text = "I was wondering if anyone out there could enlighten me on this car."

# 길이가 1~2인 단어들을 정규 표현식을 이용하여 삭제
shortword = re.compile(r'\W*\b\w{1,2}\b')  # \W는 단어가 아닌것, \w:알파벳+숫자, \b는 공백
shortword.sub('', text)

' was wondering anyone out there could enlighten this car.'

In [32]:
# 불용어 꺼내와 제거하기
from nltk.corpus import stopwords

stop_words=stopwords.words('english')
tokens=word_tokenize(text)
result=[]

for i in tokens:
    if i not in stop_words:
        result.append(i)
print(result)

['I', 'wondering', 'anyone', 'could', 'enlighten', 'car', '.']


In [34]:
# 정규표현식으로 내가 지정해서 뽑아오거나 삭제
import re
standard=re.compile(r'\w{3,}')
print(standard.findall(text))     #3글자 이상인 애를 리스트로

#nltk함수 사용
from nltk.tokenize import RegexpTokenizer
standard=RegexpTokenizer(r'\w{3,}')    #3글자 이상만 가져옴
print(standard.tokenize(text))

standard=RegexpTokenizer(r'\s+',gaps=True)  #빈칸을 기준으로 나눔
print(standard.tokenize(text))

['was', 'wondering', 'anyone', 'out', 'there', 'could', 'enlighten', 'this', 'car']
['was', 'wondering', 'anyone', 'out', 'there', 'could', 'enlighten', 'this', 'car']
['I', 'was', 'wondering', 'if', 'anyone', 'out', 'there', 'could', 'enlighten', 'me', 'on', 'this', 'car.']


## 2-2. 정규화
- 어간 추출 (stem)->의미만 알아볼 수 있게 자름->사전에 없을수 있음
- 표제어 추출 (lemmatization)-> 뿌리 단어로

In [27]:
#어간추출
from nltk.stem import PorterStemmer

sentence = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."

tokens=word_tokenize(sentence)
stemmer=PorterStemmer()
print([stemmer.stem(i) for i in tokens])

['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [30]:
# 표제어추출
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print('표제어 추출 후 :',[lemmatizer.lemmatize(i) for i in tokens])
print('표제어 추출 후 :',[lemmatizer.lemmatize(i,'v') for i in tokens]) #이때 verb옵션 넣으면 found가 find로

표제어 추출 후 : ['This', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sounding', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']
표제어 추출 후 : ['This', 'be', 'not', 'the', 'map', 'we', 'find', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'name', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'cross', 'and', 'the', 'write', 'note', '.']


# 3. 정수 인코딩(Integer Encoding)
- 텍스트를 숫자로 바꿈
- 빈도수가 높은 단어를 우선으로 낮은 숫자 부여

In [37]:
#데이터
text = """A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret!
The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word.
His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. The barber went up a huge mountain."""
text

'A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret!\nThe Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word.\nHis barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. The barber went up a huge mountain.'

### 1.문장 토큰화

In [39]:
sentences = sent_tokenize(text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'The barber went up a huge mountain.']


### 2. 단어 토큰화 후 소문자화+불용어 제거+짧은단어 제거+각 단어 빈도수 세기

In [41]:
vocab = {}    #고유 단어와 그 개수
preprocessed_sentences = []    #전처리한 문장들
stop_words = set(stopwords.words('english'))

for sentence in sentences:
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []

    for word in tokenized_sentence: 
        word = word.lower() # 모든 단어를 소문자화하여 단어의 개수를 줄인다.
        if word not in stop_words: # 단어 토큰화 된 결과에 대해서 불용어를 제거한다.
            if len(word) > 2: # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거한다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1    # 특정 단어가 나올때마다 value값을 1씩 증가
    preprocessed_sentences.append(result) 
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [42]:
# 빈도수
print('단어 집합 :',vocab)

단어 집합 : {'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


### 3. 빈도수대로 정렬

In [45]:
vocab_sorted = sorted(vocab.items(),key = lambda x:x[1], reverse = True)  #x[1]은 key,value값 중 value값을 기준으로 정렬하겠다
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


### 4. 높은 빈도수에 낮은 번호 부여(1부터)-이때 빈도수 1이하는 제거(이는 본인이 판다)

In [47]:
word_to_index = {}
i = 0
for (word, frequency) in vocab_sorted :
    if frequency > 1 : # 빈도수가 작은 단어는 제외.
        i = i + 1
        word_to_index[word] = i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


### 5. 본인의 판단하에 빈도수가 높은 상위 단어 n개 가져오기(나는 5개)

In [48]:
vocab_size = 5

# 인덱스가 5 초과인 단어 제거
words_frequency = [word for word, index in word_to_index.items() if index >= vocab_size + 1]

# 해당 단어에 대한 인덱스 정보를 삭제
for w in words_frequency:
    del word_to_index[w]
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


### 6. OOV(out of vocabulary)문제
- 일부만 가져오고 나머지는 삭제함에따라 인코딩 안된 토큰들이 존재
- 이들에게는 전부 하나의 새로운 정수로 인코딩->나는 6으로

In [49]:
#앞으로 인코딩 안되 애들에게는 6을 부여하겠다
word_to_index['OOV'] = len(word_to_index) + 1   #6
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


### 7. 각 문자와 인코딩 정수를 맵핑-인코딩 완료

In [50]:
encoded_sentences = []    #결과
for sentence in preprocessed_sentences:  #각 문장에서
    encoded_sentence = []
    for word in sentence:       #각 단어에서
        try:
            # 단어 집합에 있는 단어라면 해당 단어의 정수를 리턴.
            encoded_sentence.append(word_to_index[word])
        except KeyError:
            # 만약 단어 집합에 없는 단어라면 'OOV'의 정수를 리턴.
            encoded_sentence.append(word_to_index['OOV'])
    encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


## 다른 방법들

## 1. counter사용

In [51]:
from collections import Counter

In [52]:
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


### 평탄화

In [56]:
in_one_list=sum(preprocessed_sentences,[])  #[]옵션을 집어넣음으로써 평탄화 가능
print(in_one_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


### 빈도수세기

In [58]:
vocab = Counter(in_one_list)
print(vocab)   #딕셔너리 형태

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


### 상위 빈도수 가져오기

In [60]:
vocab_size = 5
top5 = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장
top5

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

### 빈도수 높은애들부터 낮은 수 부여

In [62]:
word_to_index = {}
i = 0
for (word, frequency) in top5 :
    i = i + 1
    word_to_index[word] = i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


### 이후 동일 과정

## 2. NLTK의 FreqDist 사용

In [63]:
from nltk import FreqDist
import numpy as np

# np.hstack으로 문장 구분을 제거
vocab = FreqDist(np.hstack(preprocessed_sentences))

vocab_size = 5
vocab = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장
print(vocab)

# 정수 부여
word_to_index = {word[0] : index + 1 for index, word in enumerate(vocab)}   #딕셔너리는 이런 형태로 컴프리헨션 가능!!!!!!!!
print(word_to_index)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


# 3. keras사용

In [64]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [65]:
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


## 자동으로 바로 빈도수대로 낮은 정수부여

In [68]:
# tokenizer() 빈칸도 가능->전부 출력
tokenizer = Tokenizer(num_words = 5 + 1) #num_words로 상위만 가져오기-> 0부터 카운트하므로 5개 사용할려면 5+1=6을 넣어줌

# fit_on_texts()안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성.
tokenizer.fit_on_texts(preprocessed_sentences)   #정수부여함수

print(tokenizer.word_counts)   #빈도수 보여줌 (전부보여주긴함)
print(tokenizer.word_index)    #이 메서드로 부여된 정수들 보여줌(이때 전부 보여주긴함)

OrderedDict({'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


## 바로 text를 인코딩

In [71]:
# text_to_sequence사용
print(tokenizer.texts_to_sequences(preprocessed_sentences))  #근데 이렇게 하면 oov는 그냥 제거

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


## 이때 oov를 넣고 싶다면 옵션 사용-> oov값은 6이 아닌 맨 처음값인 1이됨
## 빈도수 제일 높은 단어는 2부터 시작

In [73]:
vocab_size = 5  #상위 5개
tokenizer = Tokenizer(num_words = vocab_size + 2, oov_token = 'OOV')  # 예비용 하나 더 필요해서 +2, oov_token옵션과 해당 키 이름 지정->이 값이 1

tokenizer.fit_on_texts(preprocessed_sentences)  #정수 부여

print(tokenizer.texts_to_sequences(preprocessed_sentences))  #가장 빈도수 높은 애는 2, oov는 1로 인코딩

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


# 4. 패딩(padding)-길이 일치시키기

In [74]:
encoded=tokenizer.texts_to_sequences(preprocessed_sentences)
encoded

[[2, 6],
 [2, 1, 6],
 [2, 4, 6],
 [1, 3],
 [3, 5, 4, 3],
 [4, 3],
 [2, 5, 1],
 [2, 5, 1],
 [2, 5, 3],
 [1, 1, 4, 3, 1, 2, 1],
 [2, 1, 4, 1]]

## 4-1-1. 가장 긴 길이 찾기

In [80]:
max_len=max(len(i) for i in encoded)
max_len

7

## 4-1-2. 부족한 부분은 뒤에 0들로 채워넣음

In [81]:
import numpy as np

for i in encoded:
    while len(i) < max_len:
        i.append(0)       #최대길이(7)가 될때까지 0 채워넣음

padded_np = np.array(encoded)    #행렬화
padded_np

array([[2, 6, 0, 0, 0, 0, 0],
       [2, 1, 6, 0, 0, 0, 0],
       [2, 4, 6, 0, 0, 0, 0],
       [1, 3, 0, 0, 0, 0, 0],
       [3, 5, 4, 3, 0, 0, 0],
       [4, 3, 0, 0, 0, 0, 0],
       [2, 5, 1, 0, 0, 0, 0],
       [2, 5, 1, 0, 0, 0, 0],
       [2, 5, 3, 0, 0, 0, 0],
       [1, 1, 4, 3, 1, 2, 1],
       [2, 1, 4, 1, 0, 0, 0]])

## 4-2 keras사용하기 ->자동으로 최대길이 기준으로 0채워넣음
- pad_sequence사용

In [82]:
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


### pad_sequence의 기본형태

In [85]:
#앞에 0
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded = pad_sequences(encoded)
padded   #앞을 0으로 채움

array([[0, 0, 0, 0, 0, 2, 6],
       [0, 0, 0, 0, 2, 1, 6],
       [0, 0, 0, 0, 2, 4, 6],
       [0, 0, 0, 0, 0, 1, 3],
       [0, 0, 0, 3, 5, 4, 3],
       [0, 0, 0, 0, 0, 4, 3],
       [0, 0, 0, 0, 2, 5, 1],
       [0, 0, 0, 0, 2, 5, 1],
       [0, 0, 0, 0, 2, 5, 3],
       [1, 1, 4, 3, 1, 2, 1],
       [0, 0, 0, 2, 1, 4, 1]])

In [86]:
# 뒤에 0채움
padded = pad_sequences(encoded, padding='post')   #post옵션
padded

array([[2, 6, 0, 0, 0, 0, 0],
       [2, 1, 6, 0, 0, 0, 0],
       [2, 4, 6, 0, 0, 0, 0],
       [1, 3, 0, 0, 0, 0, 0],
       [3, 5, 4, 3, 0, 0, 0],
       [4, 3, 0, 0, 0, 0, 0],
       [2, 5, 1, 0, 0, 0, 0],
       [2, 5, 1, 0, 0, 0, 0],
       [2, 5, 3, 0, 0, 0, 0],
       [1, 1, 4, 3, 1, 2, 1],
       [2, 1, 4, 1, 0, 0, 0]])

### 최대길이 직접 지정

In [88]:
# 최대길이 직접 지정
padded = pad_sequences(encoded, padding='post', maxlen=5)
padded   #이때 앞에것들이 잘림

array([[2, 6, 0, 0, 0],
       [2, 1, 6, 0, 0],
       [2, 4, 6, 0, 0],
       [1, 3, 0, 0, 0],
       [3, 5, 4, 3, 0],
       [4, 3, 0, 0, 0],
       [2, 5, 1, 0, 0],
       [2, 5, 1, 0, 0],
       [2, 5, 3, 0, 0],
       [4, 3, 1, 2, 1],
       [2, 1, 4, 1, 0]])

In [89]:
# 뒤에것들이 잘리게 하기
padded = pad_sequences(encoded, padding='post', truncating='post', maxlen=5)  #truncating을 post로
padded

array([[2, 6, 0, 0, 0],
       [2, 1, 6, 0, 0],
       [2, 4, 6, 0, 0],
       [1, 3, 0, 0, 0],
       [3, 5, 4, 3, 0],
       [4, 3, 0, 0, 0],
       [2, 5, 1, 0, 0],
       [2, 5, 1, 0, 0],
       [2, 5, 3, 0, 0],
       [1, 1, 4, 3, 1],
       [2, 1, 4, 1, 0]])

### 채울 value를 직접 지정

In [91]:
# 0말고 다른 숫자 넣기
padded = pad_sequences(encoded, padding='post', value=100)  #value옵션 사용
padded

array([[  2,   6, 100, 100, 100, 100, 100],
       [  2,   1,   6, 100, 100, 100, 100],
       [  2,   4,   6, 100, 100, 100, 100],
       [  1,   3, 100, 100, 100, 100, 100],
       [  3,   5,   4,   3, 100, 100, 100],
       [  4,   3, 100, 100, 100, 100, 100],
       [  2,   5,   1, 100, 100, 100, 100],
       [  2,   5,   1, 100, 100, 100, 100],
       [  2,   5,   3, 100, 100, 100, 100],
       [  1,   1,   4,   3,   1,   2,   1],
       [  2,   1,   4,   1, 100, 100, 100]])

# 5. one-hot encoding(정수인코딩의 다른 버전)
- 표현하고 싶은 단어의 인덱스에 1의 값을 부여하고, 다른 인덱스에는 0을 부여

## 5-1. 빈도수에 따라 정수 부여

In [92]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])     #빈도수 높은 단어들에 정수 부여
print('단어 집합 :',tokenizer.word_index)    

단어 집합 : {'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


## 5-2. 고유한 단어들로만 이루어진 text생성

In [95]:
# 고유단어들만 있는 sub_text
sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded = tokenizer.texts_to_sequences([sub_text])[0]   #[[X]]형태여서 [0]해야 X나옴
print(encoded)

[2, 5, 1, 6, 3, 7]


## 5-3. to_categorical로 ->각 단어별 정수값 위치에 1이고 나머지는 0인 행들이 단어개수만큼 생성

In [96]:
one_hot = to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


## 한계->단어수가 늘어날수록 벡터차원이 늘어나 비효율적

# 6. train용과 test용 데이터 분리
- 훈련 데이터: x_train(시험지), y_train(정답)
- 테스트 데이터: x_test(시험지), y_test(정답->실제로 모델의 예측률이 얼마인지 얘를 통해 측정)

## 6-1. x(시험지)와 y(정답)분리

### zip함수

In [103]:
# 1. zip함수 사용
sequences = [['a', 1], ['b', 2], ['c', 3]]
x, y = zip(*sequences)   #*로 풀어주고 zip으로 x=a, y=1로
print('X 데이터 :',x)
print('y 데이터 :',y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


### pandas

In [104]:
# 2. pandas의 데이터프레임 사용
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [113]:
x = df['메일 본문']
y = df['스팸 메일 유무']
print(x,y)
print('----------------------------------------')
print(x.to_list())    #to_list사용하면 데이터프레임형태가 아닌 각 속성값들을 ,를 두고 리스트 안으로
print(y.to_list())

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object 0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64
----------------------------------------
['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
[1, 0, 0, 1]


###  numpy

In [114]:
np_array = np.arange(0,16).reshape((4,4))

print(np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [115]:
# 앞에 3개 컬럼을 x, 뒤의 마지막 하나를 y
X = np_array[:, :3]
y = np_array[:,3]

print('X 데이터 :')
print(X)
print('y 데이터 :',y)

X 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


## 6-2. 각각의 x,y에서 train과 test분리-random

In [116]:
from sklearn.model_selection import train_test_split

In [117]:
# x,y넣고 test_size=0.2는 전체의 20%가 테스트용, random_state=1234는 set.seed(1234)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

In [121]:
X_train,'---------------------------',X_test

(array([[ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 '---------------------------',
 array([[0, 1, 2]]))

In [123]:
y_train,'////',y_test

(array([ 7, 11, 15]), '////', array([3]))

### 다른 random state로하면 랜덤하게 나눔

In [124]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1)

In [125]:
X_train,'---------------------------',X_test

(array([[ 8,  9, 10],
        [ 0,  1,  2],
        [ 4,  5,  6]]),
 '---------------------------',
 array([[12, 13, 14]]))

In [126]:
y_train,'////',y_test

(array([11,  3,  7]), '////', array([15]))